# Book settings
title:
author: Bradley Kwalton and Edmundo Houllemont
logo: docs/images/logo.png
only_build_toc_files: false

repository:
  url: https://github.com/bkwalton/food-security-wb
  branch: main

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://bkwalton.github.io/food-security-wb
  extra_footer: |
    <div>
     We are students in the MS Applied Economics program at George Washington University in Washington, D.C. Data were sourced from the World Bank and all analysis has been completed in collaboration with World Bank employees.
    </div>
    <div>
        <b>All content (unless otherwise specified) is subject to the <a href="https://www.mozilla.org/en-US/MPL">Mozilla Public License.</a></b>
    </div>
  favicon: docs/images/favicon.ico

#######################################################################################
# Execution settings
execute:
  execute_notebooks: off

#######################################################################################
# Bibliography settings
bibtex_bibfiles:
  - docs/bibliography.bib

#######################################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"
